-- MySQL Script generated by MySQL Workbench
-- 12/16/14 16:49:43
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ActiveUsers
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ActiveUsers
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ActiveUsers` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `ActiveUsers` ;

-- -----------------------------------------------------
-- Table `ActiveUsers`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ActiveUsers`.`Users` (
  `UserID` INT NOT NULL AUTO_INCREMENT,
  `Username` VARCHAR(255) NOT NULL,
  `Password` CHAR(32) NOT NULL,
  PRIMARY KEY (`UserID`),
  UNIQUE INDEX `Username_UNIQUE` (`Username` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
