-- MySQL Script generated by MySQL Workbench
-- 12/10/14 13:01:35
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `AutoShop` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `AutoShop` ;

-- -----------------------------------------------------
-- Table `mydb`.`Brands`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AutoShop`.`Brands` (
  `BrandID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(255) NULL,
  `Country` VARCHAR(255) NULL,
  PRIMARY KEY (`BrandID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Models`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AutoShop`.`Models` (
  `ModelID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NULL,
  `BrandID` INT NOT NULL,
  `Modelscol` VARCHAR(45) NULL,
  PRIMARY KEY (`ModelID`),
  INDEX `fk_Models_Brands_idx` (`BrandID` ASC),
  CONSTRAINT `fk_Models_Brands`
    FOREIGN KEY (`BrandID`)
    REFERENCES `AutoShop`.`Brands` (`BrandID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
