-- MySQL Script generated by MySQL Workbench
-- 12/10/14 13:26:30
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema University
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema University
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `University` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `University` ;

-- -----------------------------------------------------
-- Table `University`.`Students`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `University`.`Students` (
  `StudentID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(255) NULL,
  `FacultyNumber` VARCHAR(12) NULL,
  PRIMARY KEY (`StudentID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `University`.`Course`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `University`.`Course` (
  `CourseID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(127) NULL,
  PRIMARY KEY (`CourseID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `University`.`StudentCourses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `University`.`StudentCourses` (
  `Course_CourseID` INT NOT NULL,
  `Students_StudentID` INT NOT NULL,
  PRIMARY KEY (`Course_CourseID`, `Students_StudentID`),
  INDEX `fk_Course_has_Students_Students1_idx` (`Students_StudentID` ASC),
  INDEX `fk_Course_has_Students_Course_idx` (`Course_CourseID` ASC),
  CONSTRAINT `fk_Course_has_Students_Course`
    FOREIGN KEY (`Course_CourseID`)
    REFERENCES `University`.`Course` (`CourseID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Course_has_Students_Students1`
    FOREIGN KEY (`Students_StudentID`)
    REFERENCES `University`.`Students` (`StudentID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
