CREATE TABLE Groups (
	GroupID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	Name VARCHAR(100) NOT NULL,
	Created TIMESTAMP DEFAULT NOW()
) DEFAULT COLLATE utf8_unicode_ci ;

CREATE TABLE Users (
	UserID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	UserName VARCHAR(100) NOT NULL,
	GroupID INT NOT NULL,
	INDEX usr_id (GroupID),
	FOREIGN KEY (GroupID) 
        REFERENCES Groups(GroupID)
        ON DELETE CASCADE
) DEFAULT COLLATE utf8_unicode_ci;